FROM python:3.9-slim-buster

# Install newer version of libpq
RUN apt-get update && apt-get install -y libpq-dev

# Install psycopg2-binary before pgsync
RUN pip install psycopg2-binary==2.9.3 -I --no-cache-dir
RUN pip install pgsync

# Download wait-for-it
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh


COPY /app/core/elastic/schema.json /schema.json

# Entrypoint script to handle the bootstrap and running pgsync
COPY entrypoint-pgsync.sh /entrypoint-pgsync.sh
RUN chmod +x /entrypoint-pgsync.sh

ENTRYPOINT ["/entrypoint-pgsync.sh"]
